spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://ec2-3-212-45-192.compute-1.amazonaws.com:5432/da8ofn7ssb6g6s
    username: epmzkrdsufzsjm
    password: c0794bb7b4b26066500c52d497b4bcbd2f93eb0f543eb83b3efc1bf6a1a1f397
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    open-in-view: false
    generate-ddl: true
  kafka:
    properties:
      sasl:
        jaas:
          config: org.apache.kafka.common.security.scram.ScramLoginModule required
            username="${CLOUDKARAFKA_USERNAME}" password="${CLOUDKARAFKA_PASSWORD}";
        mechanism: SCRAM-SHA-256
      security:
        protocol: SASL_SSL
    producer:
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
    consumer:
      auto-offset-reset: latest
      group-id: ${CLOUDKARAFKA_USERNAME}-consumers
      properties:
        spring:
          json:
            trusted:
              packages: sample.kafka
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
    bootstrap-servers: ${CLOUDKARAFKA_BROKERS}

topic.votacao: ${CLOUDKARAFKA_TOPIC_PREFIX}votacao
CLOUDKARAFKA_BROKERS: tricycle-01.srvs.cloudkafka.com:9094,tricycle-02.srvs.cloudkafka.com:9094,tricycle-03.srvs.cloudkafka.com:9094
CLOUDKARAFKA_USERNAME: mvcfg6d6
CLOUDKARAFKA_PASSWORD: QIy1IJsc9L2mG09-xHe43vlemU5WxDff
CLOUDKARAFKA_TOPIC_PREFIX: mvcfg6d6-

integration.cpf.baseUrl: https://user-info.herokuapp.com/users